### ISSUE TITLE
As a Developer, I want to terminate the complete session of the game by using a key button 'M' so that it closes the game all at once.

### ISSUE THREAD

**Issue by fayu555** [WSU-CEG-6110-4410/ADAD-Craft#71]
As a Player, I want to terminate the complete session of the game by using a key button 'M'.

**Comment by agreeablyblue** [comment]
I think you should choose a different key besides "M" to terminate the game session. Many games use "M" as the map key, which could cause some players to mistakenly press "M" for the map but then get kicked out of the game.

**Comment by fayu555** [comment]
Implementation has been done.
